steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--tag', 'gcr.io/astracloud/astraimage']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'astracloud', '--image', 'gcr.io/astracloud/astraimage', '--region', 'europe-west12']
